# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IHt53xEUP4xumDrKQFzlp490tBf9tFQ5
"""

import pickle

from gridworld import *
# from analyze import *

if __name__ == '__main__':
    # runtime = 100
    filename_state = 'state'
    filename_qtable = 'qtable'
    filename_results = 'results'
    number_of_robots = 2
    number_of_interestpoints = 2
    dimension = 4
    observation_size = (3, 84, 84)
    env = GridWorld(number_of_robots, number_of_interestpoints, dimension, observation_size)

    number_of_episodes = 500
    env.train(number_of_episodes)
    # analyze_convergence()
    env.visualize_training(filename_state, number_of_episodes)
    # env.evaluate(filename_qtable)
    # env.visualize(filename_results)
    env.close()
